### ISSUE TITLE
Update meta descriptions

### ISSUE THREAD

**Issue by wolfmoritz** [peareye/osc2017dynamic#14]
Write good meta descriptions for each page. Google SEO length has gone from 160 to 230 characters. 

Need to update `{% block metaDescription %}` on:
* calendar.html
* contact.html
* gallery.html
* home (can also be set in _baseLayout.html)
* rates.html
* reserve.html
* reviews.html

**Comment by peareye** [comment]
Added SEO titles and description at the metaDescription level.
